version: "3"

services:
  redis:
    image: "redis:latest"
    container_name: microservice-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - "REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL"
    labels:
      kompose.service.type: nodeport
    command:
      - redis-server
      - "--bind"
      - redis
      - "--port"
      - "6379"
    volumes:
      - ./data_store/:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - postgres_family

  message_db:
    container_name: message_db
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: message_db
      POSTGRES_HOST: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data_store/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres_family

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: core2pixel@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5440:80"
    restart: unless-stopped
    depends_on:
      - message_db
    networks:
      - postgres_family
    volumes:
      - ./data_store/pgadmin-data:/var/lib/pgadmin
    user: root
volumes:
  redis_data:
    driver: local

networks:
  postgres_family:
    driver: bridge
