export enum PopupTypes {
  CREATE_BOT_MESSAGE = "CREATE_BOT_MESSAGE",
  CREATE_COMMAND = "CREATE_COMMAND",
  UPDATE_BOT_MESSAGE = "UPDATE_BOT_MESSAGE",
  UPDATE_LINK = "UPDATE_LINK",
  REPLY_ON_MESSAGE = "REPLY_ON_MESSAGE",
}
